config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  resources :posts
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :user
  belongs_to :post

  def self.log(event_type, post)
    create(event_type: event_type, post_id: post.id, user_id: post.user_id)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, length: { minimum: 2 }
  validates :author, length: { minimum: 2 }
  validates :body, length: { minimum: 2, maximum: 999 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %w[index show]
  before_action :_post, only: :show
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      History.log(:new_post, @post)
      PostNotificationMailer.with(user: @post.user, post: @post)
                            .new_post_created
                            .deliver_now

      redirect_to posts_path
    else
      render :new
    end
  end

  def show;end

  private

  def post_params
    params.require(:post).permit(:title, :author, :body)
  end

  def _post
    @post = Post.find_by(id: params[:id])

    redirect_to "/404.html" unless @post
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SandboxRailsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="container px-4 md:px-0 max-w-6xl mx-auto">
    <nav class="flex justify-around">
      <%= link_to "Posts", posts_path, class: "flex" %>
      <a class="flex">Logs</a>
      <% if user_signed_in? %>
        <%= button_to("Log Out", destroy_user_session_path, method: :delete) %>
      <% end %>
    </nav>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/index.html.erb
<div>
  <h1 class="text-3xl">Posts</h1>

  <%= link_to("New Post", new_post_path) %>

  <div class="posts mx-auto mt-10">
    <% @posts.each_with_index do |post, index| %>
      <article class="flex w-100 rounded-lg border border-slate-300 p-2 mb-2">
        <div class="date-box mr-2">
          <div><%= post.created_at.strftime("%b %d") %></div>
          <div class="text-xl"><%= post.created_at.strftime("%Y") %></div>
        </div>
        <div class="flex-col grow">
          <h3 class="text-xl w-full">
            <%= link_to(post.title, post_path(post)) %>
          </h3>
          <p class="block">
            <%= truncate(post.body) { link_to("... read", post_path(post)) } %>
          </p>
        </div>
        <div class="pt-2">
          <p class="font-semibold text-gray-900">
              <%= post.author %>
          </p>
        </div>
      </article>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_with model: @post do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :author %>
  <%= form.text_field :author %>

  <%= form.label :body %>
  <%= form.text_area :body %>

  <%= form.submit%>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p><%= @post.body %></p>